// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateApp.Data.CalculateApp;

public partial class Estimate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string AspUserId { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<ProductsEstimate> ProductsEstimates { get; set; } = new List<ProductsEstimate>();
}