// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateApp.Data.CalculateApp;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Characteristic> Characteristics { get; set; } = new List<Characteristic>();

    public virtual ICollection<ProductsEstimate> ProductsEstimates { get; set; } = new List<ProductsEstimate>();

    public object Clone()
    {
        return this.MemberwiseClone();
    }
}