// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalculateApp.Data.CalculateApp;

public partial class Room
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double Lenght { get; set; }

    public double Width { get; set; }

    public double Height { get; set; }

    public string AspNetUserId { get; set; }
}